main: set `SilenceErrors` to avoid double error printing
We handle the errors ourselfs in bootc-image-builder but there was
a setting missing which lead to double prints:
```
$ go build && sudo ./bootc-image-builder manifest quay.io/fedora/fedora-bootc:40
Error: cannot generate manifest: cannot get rootfs type for container: container does not include a default root filesystem type
2024/06/24 10:26:42 error: cannot generate manifest: cannot get rootfs type for container: container does not include a default root filesystem type
```

This commit fixes this and adds a test:
```
$ go build && sudo ./bootc-image-builder manifest quay.io/fedora/fedora-bootc:40
2024/06/24 10:43:38 error: cannot generate manifest: cannot get rootfs type for container: container does not include a default root filesystem type
```